plugins:
  scss-lint:
    enabled: true
    checks:
      ImportantRule:
        enabled: false
      NestingDepth:
        enabled: false
      SelectorDepth:
        enabled: false
  markdownlint:
    enabled: true
